### ISSUE TITLE
Cargo unable to fetch dependency

### ISSUE THREAD

**Issue by Sup3Legacy** [thenlevy/ensnano#5]
Hello!

I have encountered an issue during the building process (more precisely during the dependency-fetching phase). Cargo refuses to load the `iced` crate.

```
error: failed to get `iced` as a dependency of package `ensnano v0.2.1`

Caused by:
  failed to load source for dependency `iced`

Caused by:
  Unable to update https://github.com/thenlevy/iced?rev=5eddea0

Caused by:
  revspec '5eddea0' not found; class=Reference (4); code=NotFound (-3)
```

It seems like the version specified in the `Cargo.toml` indicates the revision `5eddea0`, which does apparently not exist.

```toml
[dependencies]
iced = { git = "https://github.com/thenlevy/iced", rev = "5eddea0", features=["image"] }
iced_wgpu = { git = "https://github.com/thenlevy/iced", rev = "5eddea0" }
iced_graphics = { git = "https://github.com/thenlevy/iced", rev = "5eddea0" }
iced_winit = { git = "https://github.com/thenlevy/iced", rev = "5eddea0" }
iced_native = { git = "https://github.com/thenlevy/iced", rev = "5eddea0" }
```

When manually editing the `Cargo.toml` file to remove these indications, the building process runs; but stops once again (although a bit further) because `ensnano_organizer` also uses `iced` as a dependency with this conflicting revision.

## Context

```
cargo 1.53.0 (4369396ce 2021-04-27)
rustc 1.53.0 (53cb7b09b 2021-06-17)
rustup 1.24.3 (ce5817a94 2021-05-31)
OS : Pop!_OS 20.10 x86_64
```

This issue has been reproduced on the following configuration

```
rustc 1.54.0-nightly (3e99439f4 2021-05-17)
OS : MacOs 11.4 Big Sur
```

## Steps to reproduce

```
git clone https://github.com/thenlevy/ensnano
cd ensnano
cargo run
```
